name: aws
dependencies:
    # base
    - python=3.7.4
    - pip=19.3.1
    - ipython=7.8.0
    - anaconda-client=1.7.2
    # testing
    - pytest=5.2.1
    - mypy=0.660
    - flake8=3.7.8
    # data
    - numpy=1.17.2
    - pandas=0.25.2
    - scikit-learn=0.21.3
    - scipy=1.3.1
    # notebooks
    - jupyter=1.0.0
    - jupyterlab=1.1.4
    # aws
    - conda-forge::awscli=1.16.268
